import { GameMetadata } from './types';

export const GAMES_LIST: GameMetadata[] = [
  // PUZZLE & LOGIC GAMES (1-10)
  {
    id: 1,
    titleEN: "Duo Tic-Tac-Toe",
    titleID: "Tic-Tac-Toe Duo",
    descriptionEN: "Classic grid-placing game for two players matching marks on a 3x3 board.",
    descriptionID: "Permainan papan klasik untuk dua pemain yang mencocokkan tanda di papan 3x3.",
    rulesEN: "Players alternate turns placing Blue Faw (O) and Pink Man (X). First to align 3 wins.",
    rulesID: "Pemain bergantian menempatkan Faw Biru (O) dan Man Merah Muda (X). Pertama menyelaraskan 3 menang.",
    winConditionEN: "Align 3 of your marks vertically, horizontally, or diagonally.",
    winConditionID: "Sejajarkan 3 tanda Anda secara vertikal, horizontal, atau diagonal.",
    category: 'puzzle'
  },
  {
    id: 2,
    titleEN: "Four-in-a-Row",
    titleID: "Empat Berderet",
    descriptionEN: "Drop coloured tokens into a vertical grid and connect four of your colors.",
    descriptionID: "Jatuhkan token berwarna ke jaringan vertikal dan hubungkan empat warna Anda.",
    rulesEN: "Alternate dropping tokens from the top of the columns. Gravity pulls tokens to the lowest available spot.",
    rulesID: "Bergantian menjatuhkan token dari atas kolom. Gravitasi menarik token ke tempat terendah.",
    winConditionEN: "Connect 4 tokens vertically, horizontally, or diagonally.",
    winConditionID: "Hubungkan 4 token secara vertikal, horizontal, atau diagonal.",
    category: 'puzzle'
  },
  {
    id: 3,
    titleEN: "Memory Match Cards",
    titleID: "Kartu Memory",
    descriptionEN: "Cooperative or competitive grid-based flip card memorisation.",
    descriptionID: "Permainan memori mencocokkan kartu secara kooperatif atau kompetitif.",
    rulesEN: "Flip 2 cards at a time. If they match, you get a point and go again. Otherwise, turn passes.",
    rulesID: "Balikkan 2 kartu sekaligus. Jika cocok, dapatkan poin dan lanjut lagi. Jika tidak, gilirannya berlalu.",
    winConditionEN: "Find and match all card pairs; player with the most matches wins.",
    winConditionID: "Temukan dan cocokkan semua pasang kartu; pemain dengan pasangan terbanyak menang.",
    category: 'puzzle'
  },
  {
    id: 4,
    titleEN: "Spot the Difference",
    titleID: "Cari Perbedaan",
    descriptionEN: "Side-by-side cute illustrations. Find hidden dissimilarities before your partner does.",
    descriptionID: "Dua ilustrasi berdampingan yang lucu. Cari perbedaan tersembunyi dengan cepat.",
    rulesEN: "Look closely at the left and right boards. Tap where differences exist. Speed counts!",
    rulesID: "Perhatikan dekorasi kiri dan kanan. Ketuk tempat yang berbeda secara cepat.",
    winConditionEN: "Find more differences than your opponent before the timer runs out.",
    winConditionID: "Temukan lebih banyak perbedaan daripada lawan sebelum waktu habis.",
    category: 'puzzle'
  },
  {
    id: 5,
    titleEN: "Lights Out Duo",
    titleID: "Lampu Padam",
    descriptionEN: "Puzzle grid where clicking toggles the clicked bulb and its direct neighbors.",
    descriptionID: "Teka-teki kisi lampu di mana mengeklik akan mengubah kondisi lampu tetangga.",
    rulesEN: "Every click flips states (ON/OFF) of target and neighboring lights. Team up to extinguish all.",
    rulesID: "Setiap klik membalikkan status (hidup/mati) lampu target dan tetangga. Padamkan semua lampu.",
    winConditionEN: "Turn all lights completely OFF together.",
    winConditionID: "Padamkan semua lampu dari papan hingga benar-benar OFF.",
    category: 'puzzle'
  },
  {
    id: 6,
    titleEN: "Sliding Puzzle",
    titleID: "Puzzle Geser",
    descriptionEN: "Slide scrambled tiles into a complete geometric picture together.",
    descriptionID: "Geser ubin acak untuk merakit gambar geometris yang lengkap bersama-sama.",
    rulesEN: "Click tiles adjacent to the empty slot to slide them. Solve the picture collaboratively or sequentially.",
    rulesID: "Klik ubin di dekat slot kosong untuk menggesernya. Selesaikan gambar bersama atau bergantian.",
    winConditionEN: "Place all mosaic panels in exact numeric/layout order.",
    winConditionID: "Temukan urutan ubin yang tepat 1-8 atau membentuk gambar penuh.",
    category: 'puzzle'
  },
  {
    id: 7,
    titleEN: "Word Builder Race",
    titleID: "Lomba Susun Kata",
    descriptionEN: "Race to spell vocabulary words out of a shared random letter pool.",
    descriptionID: "Balapan mengeja kosa kata dari tumpukan huruf acak bersama.",
    rulesEN: "Type valid words using only the provided character bank layout. Each letter may be used once.",
    rulesID: "Ketik kata yang sah menggunakan bank huruf yang disediakan. Setiap huruf hanya dipakai sekali.",
    winConditionEN: "Earn more points by typing the longest and most complex valid words.",
    winConditionID: "Pemain dengan poin tertinggi dari kata yang sah memenangkan ronde.",
    category: 'puzzle'
  },
  {
    id: 8,
    titleEN: "Duo Hangman",
    titleID: "Hangman Berdua",
    descriptionEN: "Classic secret word guessing game. One defines, the other reveals.",
    descriptionID: "Permainan tebak kata rahasia klasik. Satu menentukan kata, lainnya menebak.",
    rulesEN: "Player 1 enters a secret prompt word. Player 2 guesses letters. Mistakes grow the platform skeleton.",
    rulesID: "Pemain 1 memasukkan kata rahasia. Pemain 2 menebak huruf. Kesalahan menggambar tiang gantungan.",
    winConditionEN: "Reveal the full word before executing 6 incorrect letter guesses.",
    winConditionID: "Tebak seluruh kata sebelum melakukan 6 kesalahan huruf.",
    category: 'puzzle'
  },
  {
    id: 9,
    titleEN: "Cooperative Sudoku Lite",
    titleID: "Sudoku Ringan",
    descriptionEN: "Mini 4x4 or 6x6 Sudoku puzzles filled collaboratively with instant error checking.",
    descriptionID: "Teka-teki Sudoku mini 4x4 atau 6x6 diisi bersama dengan pemeriksaan kesalahan langsung.",
    rulesEN: "Fill empty numbers. Numbers must not repeat in any row, column, or mini-box section.",
    rulesID: "Isi kotak kosong. Angka tidak boleh berulang dalam baris, kolom, atau wilayah kotak kecil.",
    winConditionEN: "Successfully complete the entire board with no remaining blank spots or errors.",
    winConditionID: "Berhasil mengisi seluruh papan dengan benar tanpa kesalahan.",
    category: 'puzzle'
  },
  {
    id: 10,
    titleEN: "Maze Runner Duo",
    titleID: "Lari Labirin",
    descriptionEN: "A race inside a geometric maze. Who will find the exit first?",
    descriptionID: "Balapan di dalam labirin geometris yang berliku. Siapa yang keluar duluan?",
    rulesEN: "Use arrow keys or click movement buttons to navigate from top-left start to bottom-right exit.",
    rulesID: "Gunakan tombol arah atau klik tombol navigasi dari titik awal ke titik keluar.",
    winConditionEN: "Be the first player to touch the golden exit gateway flag.",
    winConditionID: "Menjadi pemain pertama yang menyentuh bendera keluar emas.",
    category: 'puzzle'
  },

  // REACTION & SPEED GAMES (11-20)
  {
    id: 11,
    titleEN: "Fast Click Battle",
    titleID: "Pertarungan Klik Cepat",
    descriptionEN: "Random circular buttons pop up. Tap them faster than your opponent.",
    descriptionID: "Tombol lingkaran muncul acak di layar. Ketuk lebih cepat dari lawan.",
    rulesEN: "Tap targets as soon as they spawn. Correct taps add points, miss-clicks deduct.",
    rulesID: "Ketuk target saat muncul. Klik benar menambah poin, klik salah mengurangi.",
    winConditionEN: "Reach 20 points first to win the battle.",
    winConditionID: "Mencapai 20 poin terlebih dahulu untuk menang.",
    category: 'reaction'
  },
  {
    id: 12,
    titleEN: "Type Racing Duel",
    titleID: "Balapan Mengetik",
    descriptionEN: "High-speed competitive typing duel of prompt words.",
    descriptionID: "Duel mengetik kompetitif kecepatan tinggi untuk kalimat atau kata pemicu.",
    rulesEN: "Type the displayed word exactly. Typos shake the screen and stall progress.",
    rulesID: "Ketik kata yang muncul dengan tepat. Typo akan menggetarkan layar dan menunda progres.",
    winConditionEN: "Complete typing all words first with the highest speed and accuracy.",
    winConditionID: "Selesaikan semua kata terlebih dahulu dengan akurasi dan kecepatan tertinggi.",
    category: 'reaction'
  },
  {
    id: 13,
    titleEN: "Reflex Ping",
    titleID: "Refleks Ping",
    descriptionEN: "A heavy concentration test of reaction measurement.",
    descriptionID: "Uji konsentrasi tinggi untuk mengukur kecepatan reaksi Anda dalam milidetik.",
    rulesEN: "Wait for the center orb to turn green, then click instantly. Early clicks disqualify the round.",
    rulesID: "Tunggu bola tengah berubah hijau, lalu klik seketika. Klik terlalu dini dianggap gugur.",
    winConditionEN: "Achieve the lowest average response time (ms) over 3 rounds.",
    winConditionID: "Meraih waktu rata-rata respon tercepat (ms) dalam 3 ronde.",
    category: 'reaction'
  },
  {
    id: 14,
    titleEN: "Color Switch Challenge",
    titleID: "Tantangan Warna",
    descriptionEN: "Quick color matching indicator changes rapidly; match colors fast.",
    descriptionID: "Indikator warna berubah cepat, sesuaikan pilihan warna Anda sesegera mungkin.",
    rulesEN: "Match the word text with the actual visual filling color. Tap matching colored buttons.",
    rulesID: "Cocokkan teks nama warna dengan warna visual yang tampil. Ketuk tombol warna yang sesuai.",
    winConditionEN: "Score highest with continuous streak combos within 15 seconds.",
    winConditionID: "Skor tertinggi dengan kombo beruntun dalam batas 15 detik.",
    category: 'reaction'
  },
  {
    id: 15,
    titleEN: "Shape Match Race",
    titleID: "Cocok Bentuk",
    descriptionEN: "Drag or click geometric tiles to corresponding outline containers.",
    descriptionID: "Seret atau klik bentuk geometri ke dalam wadah garis luar yang cocok.",
    rulesEN: "Match the incoming triangles, clouds, and squares with their respective shadows.",
    rulesID: "Cocokkan bentuk segitiga, awan, dan persegi dengan bayangannya masing-masing.",
    winConditionEN: "Successfully match 10 designs quickest.",
    winConditionID: "Berhasil mencocokkan 10 bentuk dengan waktu tercepat.",
    category: 'reaction'
  },
  {
    id: 16,
    titleEN: "Quick Math Duel",
    titleID: "Hitung Cepat",
    descriptionEN: "Solve simple math equations in a high-tension head-to-head match.",
    descriptionID: "Selesaikan persamaan matematika sederhana dalam laga satu lawan satu yang menegangkan.",
    rulesEN: "Solve the equation. Press the correct answer button before the rival clicks it.",
    rulesID: "Selesaikan hitungan. Tekan tombol jawaban yang benar sebelum lawan mendahului.",
    winConditionEN: "Earn highest score from correct math equations within the round duration.",
    winConditionID: "Kumpulkan poin terbanyak dari persamaan yang benar dalam satu ronde.",
    category: 'reaction'
  },
  {
    id: 17,
    titleEN: "Reaction Lights Duel",
    titleID: "Lampu Reaksi",
    descriptionEN: "Grid of lights flicker randomly; tap green bulbs immediately.",
    descriptionID: "Kotak lampu berkedip acak; ketuk lampu hijau segera begitu menyala.",
    rulesEN: "Only tap the light grid when it turns solid green. Clicking red reduces score.",
    rulesID: "Hanya ketuk kotak ketika lampu hijau solid. Mengeklik merah memotong nilai.",
    winConditionEN: "Capture the most green signals in 15 seconds.",
    winConditionID: "Tangkap sinyal hijau terbanyak dalam waktu 15 detik.",
    category: 'reaction'
  },
  {
    id: 18,
    titleEN: "Speed Tapping Arena",
    titleID: "Arena Ketuk Cepat",
    descriptionEN: "Pure stamina and click speed race in a finite time window.",
    descriptionID: "Uji ketahanan fisik jari Anda dalam mengetuk layar secepatnya dalam 10 detik.",
    rulesEN: "Mash the designated blue or pink tapping button. Speed up to fill your meter.",
    rulesID: "Ketuk tombol biru atau merah muda Anda terus menerus. Isi penuh pengukur daya.",
    winConditionEN: "Register the absolute highest click count in 10 seconds empty-handed.",
    winConditionID: "Mencatatkan jumlah ketukan murni terbanyak dalam 10 detik.",
    category: 'reaction'
  },
  {
    id: 19,
    titleEN: "Swipe Race",
    titleID: "Balapan Swipe",
    descriptionEN: "Follow swift directions vectors on-screen to advance your glider.",
    descriptionID: "Ikuti instruksi panah arah geser secara beruntun untuk meluncurkan pesawat.",
    rulesEN: "Click/swipe arrow buttons matching the sequence pattern shown on your board.",
    rulesID: "Klik atau geser tombol panah sesuai pola barisan yang ditampilkan di papan.",
    winConditionEN: "Be the fastest to finish 15 complete direction key configurations.",
    winConditionID: "Menjadi yang tercepat menyelesaikan 15 konfigurasi arah dengan sempurna.",
    category: 'reaction'
  },
  {
    id: 20,
    titleEN: "Aim Training Duo",
    titleID: "Latihan Aim",
    descriptionEN: "Sinking targets shrink rapidly; aim and destroy them.",
    descriptionID: "Target bulat mengecil cepat; latih akurasi tembakan Anda dan hancurkan.",
    rulesEN: "Click small moving targets on screen. Target size diminishes over time.",
    rulesID: "Klik target bulat yang mengorbit atau bergeser di layar. Ukuran mengecil seiring waktu.",
    winConditionEN: "Earn the highest score by popping micro targets accurately.",
    winConditionID: "Peroleh skor tertinggi dengan meletuskan target mikro secara akurat.",
    category: 'reaction'
  },

  // CASUAL FUN GAMES (21-30)
  {
    id: 21,
    titleEN: "Coin Collecting Race",
    titleID: "Lomba Kumpul Koin",
    descriptionEN: "Navigate cute cloud boards capturing shiny floating sky coins.",
    descriptionID: "Kendalikan karakter awan Anda untuk mengumpulkan koin mengapung di langit.",
    rulesEN: "Move left, right, up, down using simple click pads to intercept spawning coins.",
    rulesID: "Bergerak ke kiri, kanan, atas, bawah untuk menangkap koin yang bermunculan.",
    winConditionEN: "Gather 15 coins fastest before the other explorer does.",
    winConditionID: "Ambil 15 koin tercepat sebelum penjelajah lawan melakukannya.",
    category: 'casual'
  },
  {
    id: 22,
    titleEN: "Bubble Pop Arena",
    titleID: "Arena Pecah Gelembung",
    descriptionEN: "Pop ascending soapy bubbles. Green gives bonus, gray pops deduct.",
    descriptionID: "Pecahkan gelembung sabun yang terbang naik. Gelembung hijau memberi bonus, abu-abu mengurangi.",
    rulesEN: "Click or tap circular bubble streams rising on screen. Some carry speed bursts.",
    rulesID: "Ketuk aliran gelembung yang beterbangan. Beberapa memiliki efek kecepatan tinggi.",
    winConditionEN: "Highest popped points inside the 20-second sky storm.",
    winConditionID: "Poin letusan terbanyak dalam badai gelembung langit 20 detik.",
    category: 'casual'
  },
  {
    id: 23,
    titleEN: "Draw & Guess",
    titleID: "Gambar & Tebak",
    descriptionEN: "A clean digital canvas for co-op sketch-illustration translation.",
    descriptionID: "Papan lukis digital bersih untuk menebak gambar coretan rekan Anda.",
    rulesEN: "Artist gets a target word and draws on canvas. Guesser types answers until right.",
    rulesID: "Pelukis mendapat kata rahasia dan mencoret di kanvas. Penebak mengetik jawaban.",
    winConditionEN: "Correct guess within the allocated time boundary solves the round.",
    winConditionID: "Tebakan yang benar sebelum waktu habis mengakhiri ronde dengan sukses.",
    category: 'casual'
  },
  {
    id: 24,
    titleEN: "Doodle Battle",
    titleID: "Pertarungan Doodle",
    descriptionEN: "Draw on topic inside 20 seconds. Competing drawings voted on by peers.",
    descriptionID: "Menggambar sesuai topik dalam 20 detik, lalu saling memberi penilaian hasil karya.",
    rulesEN: "Both draw based on a funny topic cue. Vote for the overall funniest or cleanest doodle.",
    rulesID: "Sama-sama menggambar topik lucu. Beri suara pada gambar yang paling rapi atau lucu.",
    winConditionEN: "Secure majority vote points from peer selections.",
    winConditionID: "Mendapat dukungan suara terbanyak dari pilihan rekan sesama.",
    category: 'casual'
  },
  {
    id: 25,
    titleEN: "Cloud Jumper Duo",
    titleID: "Lompatan Awan",
    descriptionEN: "Bounce across light sky platform layers without falling to the ground.",
    descriptionID: "Lompat meniti lapisan awan tipis di langit tanpa terjatuh ke bawah.",
    rulesEN: "Guide your character left/right onto rising clouds. Avoid storm clouds with electric properties.",
    rulesID: "Arahkan karakter ke kiri/kanan di atas awan. Hindari awan mendung berasap petir.",
    winConditionEN: "Survive longest or climb to the highest altitude level.",
    winConditionID: "Bertahan hidup paling lama atau memanjat hingga ketinggian maksimum.",
    category: 'casual'
  },
  {
    id: 26,
    titleEN: "Balloon Burst",
    titleID: "Pecah Balon",
    descriptionEN: "Tap and burst colourful party balloons floating up.",
    descriptionID: "Ketuk dan letuskan balon pesta warna-warni sebelum melayang hilang.",
    rulesEN: "Click rising balloons. Each color represents dynamic scoring tiers.",
    rulesID: "Klik balon yang terbang. Setiap warna melambangkan poin yang dinamis.",
    winConditionEN: "Collect maximum score within the allocated timeframe.",
    winConditionID: "Kumpulkan skor puncak dalam alokasi durasi permainan.",
    category: 'casual'
  },
  {
    id: 27,
    titleEN: "Mini Bowling",
    titleID: "Bolos Mini",
    descriptionEN: "Aim pins with a clean virtual slide release ball.",
    descriptionID: "Arahkan bola boling kecil untuk merubuhkan pin dengan presisi gaya dorong.",
    rulesEN: "Adjust starting angle slider, determine launch sliding velocity, and release bowling ball.",
    rulesID: "Sesuaikan sudut lintasan, atur intensitas kekuatan lempar, dan lepaskan bola boling.",
    winConditionEN: "Knock down the most pins over 3 complete frame roll-outs.",
    winConditionID: "Merubuhkan pin boling terbanyak dalam 3 kesempatan menggelinding.",
    category: 'casual'
  },
  {
    id: 28,
    titleEN: "Fruit Slice Race",
    titleID: "Iris Buah",
    descriptionEN: "Swipe across virtual fruits to chop them. Avoid hazardous spiked shapes.",
    descriptionID: "Geser kursor untuk memotong buah-buahan segar di layar. Hindari objek berduri jahat.",
    rulesEN: "Slice cascading clean fruits for combo chain score. Avoid ticking circular bombs.",
    rulesID: "Iris buah yang meluncur untuk mendapat bonus kombo. Hindari ulat atau bom.",
    winConditionEN: "Highest slice metric score without triggering 3 item explosions.",
    winConditionID: "Skor iris buah tertinggi tanpa meledakkan 3 ranjau.",
    category: 'casual'
  },
  {
    id: 29,
    titleEN: "Bottle Flip Online",
    titleID: "Lempar Botol",
    descriptionEN: "Launch a plastic drinking bottle so it lands perfectly upright on shelves.",
    descriptionID: "Lemparkan botol minum plastik agar mendarat tegak sempurna di rak awan.",
    rulesEN: "Click and hold to load launching lift force, release to make model flip. Land safely.",
    rulesID: "Klik dan tahan kekuatan melontar botol, lepaskan untuk berputar di udara.",
    winConditionEN: "Land consecutive accurate bottle flips onto targets.",
    winConditionID: "Lakukan pendaratan botol tegak beruntun terbanyak.",
    category: 'casual'
  },
  {
    id: 30,
    titleEN: "Sky Glider Co-Op",
    titleID: "Layang-Layang",
    descriptionEN: "Coordinate combined weight to fly a kite glider through sky walls.",
    descriptionID: "Koordinasikan keseimbangan beban sayap layang-layang melewati gerbang awan.",
    rulesEN: "Player 1 balances left-wing, Player 2 handles right-wing. Keep the glider centered.",
    rulesID: "Pemain 1 mengontrol sayap kiri, Pemain 2 mengatur sayap kanan. Jaga layangan di tengah.",
    winConditionEN: "Pass through 10 horizontal cloud corridors safely.",
    winConditionID: "Melewati 10 koridor awan horizontal dengan selamat.",
    category: 'casual'
  },

  // STRATEGY GAMES (31-40)
  {
    id: 31,
    titleEN: "Mini Chess",
    titleID: "Catur Mini",
    descriptionEN: "A fast-paced chess combat played on a compact 5x5 chessboard grid.",
    descriptionID: "Pertandingan catur ringkas yang taktis di atas papan catur mikro 5x5.",
    rulesEN: "Standard moves apply on a reduced field with King, Rook, Knight, Bishop, and Pawn teams.",
    rulesID: "Aturan catur standar berlaku di bidang terbatas dengan jajaran bidak miniatur.",
    winConditionEN: "Slay or trap the rival's miniature King (Checkmate).",
    winConditionID: "Sekakmat atau tangkap mahkota Raja lawan di papan catur.",
    category: 'strategy'
  },
  {
    id: 32,
    titleEN: "Micro Tower Defense",
    titleID: "Pertahanan Mini",
    descriptionEN: "Place defense cute blockers together around paths to stop balloon invaders.",
    descriptionID: "Pasang menara pemblokir untuk membayangi balon perusah di sepanjang jalur.",
    rulesEN: "Buy towers with crystal drops and build defenses along the lane to pop invaders.",
    rulesID: "Beli kubah pertahanan dengan kristal dan letakkan di jalur untuk meletuskan musuh.",
    winConditionEN: "Surviving 5 consecutive enemy balloon invasion waves fully intact.",
    winConditionID: "Sukses bertahan dari 5 gelombang serbuan balon musuh.",
    category: 'strategy'
  },
  {
    id: 33,
    titleEN: "Territory Control",
    titleID: "Kuasai Wilayah",
    descriptionEN: "Step and occupy floor hexagon grids to expand paint colors.",
    descriptionID: "Langkahi dan kuasai ubin segi enam lantai untuk menyebarkan warna Anda.",
    rulesEN: "Move on adjacent hex tiles to claim them. Claiming adjacent areas captures them.",
    rulesID: "Berjalanlah di atas ubin heksagonal untuk merubah warna ubin menjadi warna tim Anda.",
    winConditionEN: "Control more than 50% of total map grid tiles when timers expire.",
    winConditionID: "Kuasai lebih dari 50% ubin heksagonal ketika waktu habis.",
    category: 'strategy'
  },
  {
    id: 34,
    titleEN: "Turn-Based Battle Board",
    titleID: "Papan Pertarungan",
    descriptionEN: "Grid battle RPG duel utilizing Action points to decide turns.",
    descriptionID: "Duel RPG taktis menggunakan Poin Aksi (AP) untuk menyerang atau bertahan.",
    rulesEN: "Allocate points for Movement, Melee striking, Shield blocking, or Healing spells on grid.",
    rulesID: "Gunakan poin aksi untuk bergerak, memukul, bertahan dengan perisai, atau memulihkan HP.",
    winConditionEN: "Reduce opponent's battle Health points to exactly 0.",
    winConditionID: "Kurangi poin kesehatan (HP) lawan hingga 0.",
    category: 'strategy'
  },
  {
    id: 35,
    titleEN: "Card Clash Lite",
    titleID: "Pertarungan Kartu",
    descriptionEN: "A clean math math-clash card deck duel. Simple and elegant.",
    descriptionID: "Pertarungan kartu angka sederhana yang bersih. Sangat taktis dan mudah dipahami.",
    rulesEN: "Draft attack, guard, and heal cards. Lay one down secretly; reveal simultaneously.",
    rulesID: "Pilih kartu serang, tangkis, atau pulih. Taruh satu kartu, buka bersamaan.",
    winConditionEN: "Outwit the rival's deck and secure 3 tier victories.",
    winConditionID: "Atur strategi kartu Anda dan menangkan 3 ronde bentrokan kartu.",
    category: 'strategy'
  },
  {
    id: 36,
    titleEN: "Path Maker Strategy",
    titleID: "Pembuat Jalur",
    descriptionEN: "Connect starting hex tiles to destination gates using link vectors.",
    descriptionID: "Hubungkan petak awal ke petak gerbang keluar dengan ubin konektor.",
    rulesEN: "Rotate and fit path tiles correctly. Do not block your rival's bridges unless tactical.",
    rulesID: "Putar dan letakkan ubin jalan. Hubungkan jembatan tanpa terputus.",
    winConditionEN: "Complete continuous road connection from start point to destination first.",
    winConditionID: "Berhasil menyusun jembatan penghubung tak terputus pertama kali.",
    category: 'strategy'
  },
  {
    id: 37,
    titleEN: "Island Builder Duo",
    titleID: "Pembangun Pulau",
    descriptionEN: "Collaboratively raise geometric mountains and plant dense trees to enrich a paradise island.",
    descriptionID: "Bangun gunung geometris dan tanam pohon hijau di pulau surga bersama.",
    rulesEN: "Take turns placing mountains, forestation tiles, water basins to hit score objectives.",
    rulesID: "Bergantian meletakkan ubin daratan, hutan, atau danau air untuk mencapai target.",
    winConditionEN: "Optimize placement bonuses together to score 100 Co-op points.",
    winConditionID: "Optimalkan bonus kombinasi tata letak untuk meraih 100 poin kerja sama.",
    category: 'strategy'
  },
  {
    id: 38,
    titleEN: "Bridge Construction",
    titleID: "Bangun Jembatan",
    descriptionEN: "Place supports across a deep cloud gorge so safe vehicles can navigate.",
    descriptionID: "Pasang struktur balok melintasi jurang awan agar dilewati mobil kecil.",
    rulesEN: "Connect connection nodes with wood and steel within structural budget limits.",
    rulesID: "Hubungkan tiang-tiang penyangga memakai kayu dan baja dengan anggaran terbatas.",
    winConditionEN: "Build a solid structure that supports full vehicle transit test weight safely.",
    winConditionID: "Bangun struktur kokoh yang berhasil dilewati uji coba kendaraan.",
    category: 'strategy'
  },
  {
    id: 39,
    titleEN: "Resource Rush",
    titleID: "Serbuan Sumber",
    descriptionEN: "Mine crystals and gather fresh cloud essence on dynamic grids.",
    descriptionID: "Tambang kristal berkilau dan kumpulkan sari awan di ubin dinamis.",
    rulesEN: "Deploy harvesting flags to harvest nodes. Defend extraction zones with shields.",
    rulesID: "Letakkan bendera panen untuk menambang mineral. Lindungi zona dengan tameng.",
    winConditionEN: "Amass a fortune of 50 shiny crystals deepest first.",
    winConditionID: "Kumpulkan deposit kekayaan 50 kristal berkilau pertama kali.",
    category: 'strategy'
  },
  {
    id: 40,
    titleEN: "Base Capture",
    titleID: "Rebutan Benteng",
    descriptionEN: "Occupy glowing beacon hubs on a layout grid to capture key strongholds.",
    descriptionID: "Kuasai lingkar suar cahaya di peta untuk menduduki benteng strategis.",
    rulesEN: "Stay within target beacon zones to build ownership indicators. Keep opponents away.",
    rulesID: "Berdiri dalam zona suar bulat untuk mengisi indikator kepemilikan Anda.",
    winConditionEN: "Raise and keep your banner flag on both base points for 10 consecutive seconds.",
    winConditionID: "Kuasai dan pertahankan bendera Anda di kedua suar selama 10 detik.",
    category: 'strategy'
  },

  // PARTY GAMES (41-50)
  {
    id: 41,
    titleEN: "Would You Rather",
    titleID: "Pilih Mana",
    descriptionEN: "A friendly dilemma choice analyzer where players lock answers and review stats.",
    descriptionID: "Dilema pilihan ramah di mana para pemain mengunci jawaban dan melihat persentase suara.",
    rulesEN: "Read options A and B. Select your preferred choice. Sync options live.",
    rulesID: "Baca pilihan A dan B. Pilih jawaban paling disukai. Hasil polling disinkronkan langsung.",
    winConditionEN: "Match answers with other room members for a synergy rating.",
    winConditionID: "Cocokkan jawaban Anda dengan anggota ruangan untuk menguji keselarasan.",
    category: 'party'
  },
  {
    id: 42,
    titleEN: "Truth or Task (Clean)",
    titleID: "Jujur atau Tantangan",
    descriptionEN: "Daring and disclosure party game. Strictly clean and family-friendly prompts.",
    descriptionID: "Permainan kejujuran atau tantangan yang bersih dan aman untuk keluarga.",
    rulesEN: "Choose TRUTH or TASK. Complete friendly actions or share interesting facts.",
    rulesID: "Pilih JUJUR (Truth) atau TANTANGAN (Task). Selesaikan perintah seru.",
    winConditionEN: "Accept, complete, and verify tasks together using room feedback.",
    winConditionID: "Terima dan selesaikan tantangan bersama dengan konfirmasi dari teman.",
    category: 'party'
  },
  {
    id: 43,
    titleEN: "Guess the Drawing",
    titleID: "Tebak Gambar",
    descriptionEN: "Scribble on dynamic canvas and challenge player friends with fast letter hints.",
    descriptionID: "Coret papan gambar digital cepat dan uji teman menebak dengan bantuan petunjuk huruf.",
    rulesEN: "Take turns drawing visually based on word prompt. Other players type exact word answers.",
    rulesID: "Bergantian melukis menurut kata kunci. Pemain lain aktif mengetik tebakan kata.",
    winConditionEN: "Guess the sketch correctly first inside the countdown timer to earn top points.",
    winConditionID: "Menebak coretan kuas tercepat sebelum durasi hitung mundur berakhir.",
    category: 'party'
  },
  {
    id: 44,
    titleEN: "Emoji Quiz",
    titleID: "Tebak Emoji",
    descriptionEN: "Decode complex film titles, cities, or food ingredients hidden in emojis.",
    descriptionID: "Pecahkan sandi nama film, kota, atau kuliner yang disembunyikan dalam barisan emoji.",
    rulesEN: "Decrypt symbol pairs. Enter raw keyboard characters representing correct solution translations.",
    rulesID: "Pecahkan teka-teki gabungan emoji. Ketik baris kosa kata yang diwakilinya.",
    winConditionEN: "Crack three consecutive emoji chains fastest and earn point trophies.",
    winConditionID: "Menjawab tiga rantaian emoji beruntun dengan paling cepat.",
    category: 'party'
  },
  {
    id: 45,
    titleEN: "Number Guess Challenge",
    titleID: "Tebak Angka",
    descriptionEN: "A math riddle logic match targeting a hidden magic constant with higher/lower cues.",
    descriptionID: "Tantangan tebak nomor rahasia acak dengan panduan arahan HIGHER atau LOWER.",
    rulesEN: "Input numbers between 1 and 100. Analyze feedback indicators to make optimal guesses.",
    rulesID: "Masukkan angka antara 1 dan 100. Analisis petunjuk arah angka rahasia.",
    winConditionEN: "Locate and isolate the correct secret number in fewer total moves than rivals.",
    winConditionID: "Menemukan angka rahasia dalam jumlah langkah tersedikit.",
    category: 'party'
  },
  {
    id: 46,
    titleEN: "Song Guessing",
    titleID: "Tebak Lagu",
    descriptionEN: "Identify globally famous song titles based on unique text snippet quotes.",
    descriptionID: "Pecahkan judul lagu populer dunia bersumber dari potongan lirik tertulis.",
    rulesEN: "Read the lyrics fragment. Pick or type correct global titles matching the audio vibe.",
    rulesID: "Baca cuplikan lirik puitis di layar. Ketik judul lagu asli yang cocok.",
    winConditionEN: "Accrue top score metrics by identifying tracks inside tight intervals.",
    winConditionID: "Dapatkan skor tertinggi dari menebak lagu dalam waktu sesingkat mungkin.",
    category: 'party'
  },
  {
    id: 47,
    titleEN: "Memory Story",
    titleID: "Cerita Memori",
    descriptionEN: "Compose crazy stories by alternating single sequential words inside strict rule turns.",
    descriptionID: "Susun cerita konyol bersama-sama dengan menambahkan satu kata kunci secara bergantian.",
    rulesEN: "Review the current running paragraph. Add exactly one logical word to expand the tale.",
    rulesID: "Baca kelanjutan dongeng. Tambahkan tepat satu kata yang logis saat giliran Anda.",
    winConditionEN: "Maintain narrative integrity without grammar errors or timer delays over 10 cycles.",
    winConditionID: "Pertahankan kelangsungan cerita tanpa kesalahan bahasa selama 10 putaran.",
    category: 'party'
  },
  {
    id: 48,
    titleEN: "Trivia Duel",
    titleID: "Trivia Duel",
    descriptionEN: "Multiplayer quiz testing general knowledge, science, internet memes, and geography.",
    descriptionID: "Duel kuis seru menguji wawasan umum, sains, budaya meme, serta geografi dunia.",
    rulesEN: "Analyse multiple choice questions. Hurry to select the correct prompt. Wrong choices lose points.",
    rulesID: "Analisis pertanyaan pilihan ganda. Tekan pilihan yang benar secepatnya.",
    winConditionEN: "Secure highest cumulative points at the conclusion of 5 random questions.",
    winConditionID: "Meraih poin tertinggi di akhir 5 pertanyaan kuis acak.",
    category: 'party'
  },
  {
    id: 49,
    titleEN: "Fast Polls",
    titleID: "Polling Cepat",
    descriptionEN: "Create dynamic questions, gather immediate answers, and compare group feedback.",
    descriptionID: "Membuat pertanyaan lucu secara instan, mengumpulkan suara grup, dan meninjau grafik.",
    rulesEN: "One player acts as polling captain typing questions. Others lock answers dynamically.",
    rulesID: "Satu pemain menjadi kapten pengusul polling. Pemain lain memilih opsi suara.",
    winConditionEN: "Collect all votes and render the full room statistical bento charts.",
    winConditionID: "Semua suara terkumpul lengkap dan bagan visual statistik bento dimunculkan.",
    category: 'party'
  },
  {
    id: 50,
    titleEN: "Duo Adventure Mini-RPG",
    titleID: "Petualangan Duo",
    descriptionEN: "A cute co-op pocket adventurer sliding on maps, looting golden keys, and fighting balloons.",
    descriptionID: "RPG petualangan mini kooperatif: jelajahi peta, jarah kunci emas, dan lawan balon jahat.",
    rulesEN: "Guide your miniature avatar to steps on switch pads to open paths for your partner.",
    rulesID: "Arahkan jagoan mini Anda menginjak tombol lantai guna membuka jalan untuk teman Anda.",
    winConditionEN: "Unlock the final golden treasure room together with shared health bar safety.",
    winConditionID: "Membuka peti gerbang harta karun akhir bersama dengan bar kesehatan (HP) utuh.",
    category: 'party'
  }
];
